[package]
name = "fsync"
version.workspace = true
authors.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = { workspace = true }
async-trait = { workspace = true }
camino = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
google-drive3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
yup-oauth2 = { workspace = true }

base64 = "0.21"
rand = "0.8"
rust-crypto = "0.2"
