[package]
name = "fsync"
version.workspace = true
authors.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = { workspace = true }
async-trait = { workspace = true }
camino = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tarpc = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
yup-oauth2 = { workspace = true }

base64 = "0.21"
dashmap = { version = "5.5.3", features = ["serde"] }
glob = "0.3.1"
google-drive3 = "^5.0"
hyper = { version = "0.14.27", features = ["stream"] }
hyper-rustls = "0.24.2"
rand = "0.8"
webbrowser = "0.8.12"
dirs = "5.0.1"
bincode = "1.3.3"
aes = "0.8.3"
ctr = "0.9.2"
tokio-util = { version = "0.7.10", features = ["compat"] }
