[package]
name = "fsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

base64 = "0.21"
rand = "0.8"
rust-crypto = "0.2"
thiserror = "1.0.50"
camino = "1.1.6"
