[package]
name = "gdrive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fsync = { path = "../fsync" }
google-drive3 = "^5.0"
hyper = "0.14.27"
hyper-rustls = "0.24.2"
