[package]
name = "fsynctl"
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
fsync = { path = "../fsync" }

camino = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
yup-oauth2 = { workspace = true }

clap = { version = "4.4.11", features = ["derive"] }
inquire = { version = "0.6.2", features = ["editor"] }
