[package]
name = "fsyncd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fsync = { path = "../fsync" }
gdrive = { path = "../gdrive" }

tokio = { workspace = true }
tokio-stream = { workspace = true }
