on: [push]

name: Check & Test 

jobs:
  test:

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{matrix.os}} 
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
